name: SARS2_28Dec2019_Genbank_submission
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - altair=5.2
  - biopython=1.82
  - entrez-direct=16.2
  - jupyterlab
  - mafft=7.520
  - pandas=2.1
  - python=3.11
  - snakemake=8.0
